//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlantillaWeb19.LoginITSON {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginITSON.AuthADServiceSoap")]
    public interface AuthADServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento domain del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsAuth", ReplyAction="*")]
        PlantillaWeb19.LoginITSON.IsAuthResponse IsAuth(PlantillaWeb19.LoginITSON.IsAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<PlantillaWeb19.LoginITSON.IsAuthResponse> IsAuthAsync(PlantillaWeb19.LoginITSON.IsAuthRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAuthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAuth", Namespace="http://tempuri.org/", Order=0)]
        public PlantillaWeb19.LoginITSON.IsAuthRequestBody Body;
        
        public IsAuthRequest() {
        }
        
        public IsAuthRequest(PlantillaWeb19.LoginITSON.IsAuthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAuthRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string domain;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string us;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pass;
        
        public IsAuthRequestBody() {
        }
        
        public IsAuthRequestBody(string domain, string us, string pass) {
            this.domain = domain;
            this.us = us;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAuthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAuthResponse", Namespace="http://tempuri.org/", Order=0)]
        public PlantillaWeb19.LoginITSON.IsAuthResponseBody Body;
        
        public IsAuthResponse() {
        }
        
        public IsAuthResponse(PlantillaWeb19.LoginITSON.IsAuthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAuthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IsAuthResult;
        
        public IsAuthResponseBody() {
        }
        
        public IsAuthResponseBody(string IsAuthResult) {
            this.IsAuthResult = IsAuthResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthADServiceSoapChannel : PlantillaWeb19.LoginITSON.AuthADServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthADServiceSoapClient : System.ServiceModel.ClientBase<PlantillaWeb19.LoginITSON.AuthADServiceSoap>, PlantillaWeb19.LoginITSON.AuthADServiceSoap {
        
        public AuthADServiceSoapClient() {
        }
        
        public AuthADServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthADServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthADServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthADServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PlantillaWeb19.LoginITSON.IsAuthResponse PlantillaWeb19.LoginITSON.AuthADServiceSoap.IsAuth(PlantillaWeb19.LoginITSON.IsAuthRequest request) {
            return base.Channel.IsAuth(request);
        }
        
        public string IsAuth(string domain, string us, string pass) {
            PlantillaWeb19.LoginITSON.IsAuthRequest inValue = new PlantillaWeb19.LoginITSON.IsAuthRequest();
            inValue.Body = new PlantillaWeb19.LoginITSON.IsAuthRequestBody();
            inValue.Body.domain = domain;
            inValue.Body.us = us;
            inValue.Body.pass = pass;
            PlantillaWeb19.LoginITSON.IsAuthResponse retVal = ((PlantillaWeb19.LoginITSON.AuthADServiceSoap)(this)).IsAuth(inValue);
            return retVal.Body.IsAuthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PlantillaWeb19.LoginITSON.IsAuthResponse> PlantillaWeb19.LoginITSON.AuthADServiceSoap.IsAuthAsync(PlantillaWeb19.LoginITSON.IsAuthRequest request) {
            return base.Channel.IsAuthAsync(request);
        }
        
        public System.Threading.Tasks.Task<PlantillaWeb19.LoginITSON.IsAuthResponse> IsAuthAsync(string domain, string us, string pass) {
            PlantillaWeb19.LoginITSON.IsAuthRequest inValue = new PlantillaWeb19.LoginITSON.IsAuthRequest();
            inValue.Body = new PlantillaWeb19.LoginITSON.IsAuthRequestBody();
            inValue.Body.domain = domain;
            inValue.Body.us = us;
            inValue.Body.pass = pass;
            return ((PlantillaWeb19.LoginITSON.AuthADServiceSoap)(this)).IsAuthAsync(inValue);
        }
    }
}
